const questions = [
  { text: "Sosyal ortamlarda kendimi rahat hissederim.", reverse: true },
  { text: "Rutin dışı değişiklikler beni rahatsız eder.", reverse: false },
  { text: "Başkalarının duygularını anlamakta zorlanırım.", reverse: false },
  { text: "Hobilerime ve ilgilerime uzun süre bağlı kalırım.", reverse: false },
  { text: "Bir konuyu detaylı düşünürüm.", reverse: true },
  { text: "Toplumsal kuralları anlamakta zorlanırım.", reverse: false },
  { text: "Yeni insanlarla tanışmak benim için zordur.", reverse: false },
  { text: "Göz teması kurmak benim için rahatsız edicidir.", reverse: false },
  { text: "Duygularımı ifade etmekte zorlanırım.", reverse: false },
  { text: "Yalnız kalmayı tercih ederim.", reverse: true },
  { text: "Seslere karşı aşırı duyarlıyımdır.", reverse: false },
  { text: "Mimikleri ve beden dilini anlamakta zorlanırım.", reverse: false },
  { text: "Sürekli aynı şeyleri yapmayı tercih ederim.", reverse: false },
  { text: "Bir hikaye okurken karakterleri kolayca hayal ederim.", reverse: true },
  { text: "Sosyal ipuçlarını anlamakta zorlanırım.", reverse: false },
  { text: "Anlamadığım konularda soru sormaktan çekinmem.", reverse: true },
  { text: "Karmaşık sosyal durumlarda nasıl davranacağımı bilemem.", reverse: false },
  { text: "Plan yapmadan hareket etmekte zorlanırım.", reverse: false },
  { text: "Duyarlı ve analitik düşünürüm.", reverse: true },
  { text: "Toplum içinde dikkat çekmek istemem.", reverse: true },
  { text: "Kelimelerin ve ifadelerin arkasındaki anlamı hemen anlayamam.", reverse: false },
  { text: "Çevremdeki küçük seslere ve ayrıntılara kolayca dikkat ederim.", reverse: false },
  { text: "Başkalarının fark etmediği detayları fark ederim.", reverse: false },
  { text: "Yeni durumlara alışmakta zorlanırım.", reverse: false },
  { text: "Konuşmalar sırasında sık sık konudan koparım.", reverse: false }
];
